hw 2
v-mk-s/prep-2021-02 pull request #7
Opened 2021-10-22 12:23 UTC by v-mk-s

Сделал 2е дз (кроме тестирующего модуля), отправляю на 1е ревью. В файлах test.c и test.h описан тестирующий модуль. Все функции закомментированы, т.к. не дописаны.

2021-10-23 14:53 UTC, alexey-ershkov requested changes
Очень хорошая домашка, но все таки нужно вынести в отдельный таргет сборки тестирующую функцию, чтобы не комментить

2021-10-25 09:41 UTC, alexey-ershkov requested changes

2021-10-27 14:37 UTC, alexey-ershkov approved these changes

2021-12-26 12:31 UTC, leshiy1295 requested changes
Можете поправить в течение недели и прислать на повторную проверку!

2022-02-27 18:30 UTC, merged